const userActionTypes = {
    RETRIEVED_USERS: "RETRIEVED_USERS",
    UPDATE_NEW_USER_DETAILS: "UPDATE_NEW_USER_DETAILS",
    CREATED_USER: "CREATED_USER",
    CLEAR_NEW_USER: "CLEAR_NEW_USER",
    SWITCH_TAB: "SWITCH_TAB"
};
export default userActionTypes;